name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - shell: bash
        run: deno run -A https://deno.land/x/edcb@v0.6.0-alpha/cli.ts
